Bump jenkins baseline to 2.319.3, parent pom and needed dependencies
jenkinsci/active-directory-plugin pull request #142
Opened 2022-11-14 14:58 UTC by raul-arabaolaza

There were failures in PCT runs against the upcoming 2.375.1 LTS due to out of date test dependencies.

Reproduced by `mvn test -Djenkins.version=2.375`  

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-11-14 16:29 UTC, jglick reviewed
Use `bom`, and delete any `<version>`s that are no longer required.

2022-11-14 16:29 UTC, jglick commented on pom.xml
> +    <configuration-as-code.version>1569.vb_72405b_80249</configuration-as-code.version>
Should be taken from BOM.

2022-11-14 16:29 UTC, jglick commented on pom.xml
> +      <version>2.9.3-65.v6a_47d0f4d1fe</version>
IIRC this as well.

2022-11-14 16:29 UTC, jglick commented on pom.xml
>      <java.level>8</java.level>
```suggestion
```

2022-11-14 16:35 UTC, basil requested changes
Based on https://ci.jenkins.io/job/Plugins/job/active-directory-plugin/job/PR-134/3/console I think this will also need an update of the Docker image used in the functional tests as described in https://github.com/jenkinsci/active-directory-plugin/pull/134#issuecomment-1259777266.

2022-11-16 10:13 UTC, raul-arabaolaza commented
I am now using the BOM, I will check testcontainers for that it failure

2022-11-16 11:58 UTC, jglick approved these changes

2022-11-16 15:09 UTC, rsandell approved these changes

2022-11-17 11:21 UTC, raul-arabaolaza commented
Anyone knows the source of the `fbelzunc/ad-build-container-with-docker-fixtures` image? I have been unable to find the dockerfile in dockerhub and https://github.com/jenkinsci/active-directory-plugin/blob/master/src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/Dockerfile is not it, the cmd instructions are different

2022-11-17 14:37 UTC, jglick commented
Did you ask @fbelzunc?

For the future, I would recommend using Testcontainers in the mode that you can build an image from source in the project. Slower (depending on cache setup) but easier to maintain and understand.

2022-11-18 08:24 UTC, raul-arabaolaza commented
Yes, but he is not available until Monday, that is why I asked here just in case. Totally agree with using testcontainers building from source, that is why I want the source Dockerfile

2022-11-21 08:16 UTC, fbelzunc commented
I think it is https://github.com/fbelzunc/active-directory-plugin-build-container-with-docker-fixtures

2022-11-24 10:50 UTC, raul-arabaolaza commented
I have been reviewing the Dockerfile that Felix linked and I do not believe I can replace it with test containers or any other thing.

IIUC that is used to run integration tests in a system with a known host name, the tests themselves use dockerfixtures that could be replaced with testcontainers, but I see no way to ensure running those tests in a controlled hostname using testcontainers, more than probably due to my lack of knowledge. Having the tests consult the hostname of the system where they are run looks less than ideal to me and may introduce portability issues.

Doing a big refactoring of the tests to address this issues is totally out of the scope of this pr and my knowledge, so I will simply update the docker image

2022-11-29 10:27 UTC, raul-arabaolaza commented
Fix for the docker image in https://github.com/fbelzunc/active-directory-plugin-build-container-with-docker-fixtures/pull/1 waiting for @fbelzunc now. I have tested it locally and is able to run the tests without issues

2022-11-29 13:02 UTC, jglick commented
> lacking permissions my changes on the Jenkinsfile would not be reflected

Hmm, https://issues.jenkins.io/browse/JENKINS-46795 again.

If you want to be a maintainer of the plugin, simply file a PR to RPU and I imagine we can get that sorted out.

> consolidate the `Dockerfile` in the plugin

Back to https://github.com/jenkinsci/active-directory-plugin/pull/142#issuecomment-1318733418? AFAICT you could just switch https://github.com/jenkinsci/active-directory-plugin/blob/be2f9e600e11981e1a5fb1f8fe56125db4fabf01/Jenkinsfile#L11-L16 to do something like

```groovy
 stage('maven') { 
    sh 'docker build -t fixture src/test/resources/fixture && docker run --add-host=samdom.example.com:127.0.0.1 -v /var/lib/docker --privileged --dns=127.0.0.1 --dns=8.8.8.8 -v $WORKSPACE:/project fixture clean install -P \'!noIT\'' 
 } 
```

2022-11-29 13:03 UTC, jglick commented
Hmm, https://github.com/jenkins-infra/repository-permissions-updater/blob/58c9d82ed5f0af1d859447b856d6f85c21503526/permissions/plugin-active-directory.yml#L18 says you are already a maintainer, so if you happen to lack write permission to the repository, just https://github.com/jenkins-infra/helpdesk/issues/new?assignees=&labels=github-permissions%2Ctriage&template=3-github-permissions.yml

2022-11-29 16:09 UTC, car-roll approved these changes

2022-11-30 09:47 UTC, merged

2022-11-30 14:27 UTC, jglick commented
@fbelzunc I guess you could archive https://github.com/fbelzunc/active-directory-plugin-build-container-with-docker-fixtures now.