[JENKINS-73827] checkin password length at login with AD plugin in FIPS mode
jenkinsci/active-directory-plugin pull request #202
Opened 2024-09-27 12:02 UTC by nevingeorgesunny

2024-09-30 06:43 UTC, olamy requested changes

2024-09-30 06:43 UTC, olamy commented on src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
> +import io.jenkins.cli.shaded.org.apache.commons.lang.StringUtils;
use package `org.apache.commons.lang`

2024-09-30 06:43 UTC, olamy commented on src/test/java/hudson/plugins/active_directory/docker/FIPSActiveDirectoryLoginTest.java
> + * Time: 7:25 pm
not needed

2024-10-02 13:50 UTC, rsandell commented
@nevingeorgesunny  Is this still a draft PR that is going to move forward or should it be closed?

2024-10-03 12:27 UTC, closed without merging